import java.util.ArrayList;

static class Sentence {
  int id;
  String text;

  Sentence(String text) {
    this.text = text;
  }

  static ArrayList<Sentence> createSentenceDatabase() {
    ArrayList<Sentence> sentenceDatabase = new ArrayList<Sentence>();

    // Add sentences to the database
    // sentenceDatabase.add(new Sentence("Did you know... "));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate different variations of a musical theme, allowing composers to explore different possibilities"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music that is influenced by the musical preferences of a specific culture or time period"));
    sentenceDatabase.add(new Sentence("Did you know... AI can compose music that tells a story or conveys a narrative"));
    sentenceDatabase.add(new Sentence("Did you know... the music that you are going to hear is 100% generated by an artificial intellignece"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music that simulates the styles of specific artists, even if they never composed in that particular genre"));
    sentenceDatabase.add(new Sentence("Did you know... AI can compose music that is inspired by visual art, translating images into musical compositions and vice versa"));
    sentenceDatabase.add(new Sentence("Did you know... AI-generated music is continuously evolving and improving, with each iteration pushing the boundaries of musical creativity"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music in different tempos and styles, catering to a wide range of preferences and applications"));
    sentenceDatabase.add(new Sentence("Did you know... AI-powered music composition tools can assist in creating custom soundtracks for videos, enhancing the overall storytelling experience"));
    sentenceDatabase.add(new Sentence("Did you know... AI can analyze the emotional content of lyrics and compose music that complements the underlying sentiment"));
    sentenceDatabase.add(new Sentence("Did you know... AI-powered music recommendation systems can suggest new songs and artists based on individual listening habits and preferences"));
    sentenceDatabase.add(new Sentence("Did you know... AI algorithms can analyze the emotional response of listeners to music and adapt compositions to elicit specific reactions"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music in different cultural styles, enabling cross-cultural exploration and fostering musical diversity"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate melodies and harmonies that push the boundaries of traditional music theory, exploring new and unconventional sounds"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate personalized music playlists based on individual preferences, adapting to the listener's taste"));
    sentenceDatabase.add(new Sentence("Did you know... AI can create entire orchestral arrangements, simulating the sound of multiple instruments playing together"));
    sentenceDatabase.add(new Sentence("Did you know... AI systems can learn from a database of existing songs and generate original compositions that blend different musical styles"));
    sentenceDatabase.add(new Sentence("Did you know... AI can analyze emotional patterns in music and compose pieces that evoke specific moods, such as happiness, sadness, or excitement"));
    sentenceDatabase.add(new Sentence("Did you know... AI can collaborate with human musicians, improvising and responding to their playing in real-time"));
    sentenceDatabase.add(new Sentence("Did you know... AI algorithms can adapt music in real-time, making it responsive to changes in the environment or user input"));
    sentenceDatabase.add(new Sentence("Did you know... AI-powered systems can generate endless variations of a musical theme, providing musicians with a rich source of inspiration and ideas"));
    sentenceDatabase.add(new Sentence("Did you know... AI can compose original music pieces, creating unique melodies and harmonies"));
    sentenceDatabase.add(new Sentence("Did you know... AI can mimic the musical style of famous composers, such as Bach or Mozart, by learning from their compositions"));
    sentenceDatabase.add(new Sentence("Did you know... AI-generated music has been used in film soundtracks and commercials"));
    sentenceDatabase.add(new Sentence("Did you know... AI can learn to improvise and generate unique musical phrases"));
    sentenceDatabase.add(new Sentence("Did you know... AI can analyze music patterns across genres and create hybrid musical styles"));
    sentenceDatabase.add(new Sentence("Did you know... AI can create remixes and mashups by combining elements from different songs"));
    sentenceDatabase.add(new Sentence("Did you know... AI can compose music for video games, tailoring the soundtrack to match the gameplay"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music that imitates specific historical periods or cultural styles"));
    sentenceDatabase.add(new Sentence("Did you know... AI can compose music in different genres, from rock and pop to jazz and electronic"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music that adapts to the listener's physiological responses, such as heart rate or brainwave activity"));
    sentenceDatabase.add(new Sentence("Did you know... AI can create music compositions that integrate elements from different cultures and traditions"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music that is specifically designed for therapy and mental health treatments"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music in different time signatures and unconventional rhythmic patterns"));
    sentenceDatabase.add(new Sentence("Did you know... AI can create music that is tailored for specific instruments or ensembles"));
    sentenceDatabase.add(new Sentence("Did you know... AI can generate music that mimics the sounds of nature, like birdsongs or ocean waves"));

    return sentenceDatabase;
  }
}
